# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


places = Place.create([
  {name: "Ülejõe kohvik"}, 
  {name: "Aleksander"}, 
  {name: "Amsterdam Kohvik/Pubi"}, 
  {name: "Asian Chef"}, 
  {name: "Big Ben Pubi"}, 
  {name: "Cafe Shakespeare"}, 
  {name: "Cafe Shogun"},  
  {name:  "Cafe Truffe"},  
  {name:  "Emajõe Pruulikoda"},  
  {name:  "Entri"},  
  {name:  "Fasters Grill-Buffee"},  
  {name:  "Fii Restoran"},  
  {name:  "Gustav Gastro Cafe"},  
  {name:  "Hektor Cafe"},  
  {name:  "Himaalaja jutud"},  
  {name:  "Hot Pot"},  
  {name:  "Illegaard"},  
  {name:  "JOP Antonius kohvik-resto"},  
  {name:  "Joyce"},  
  {name:  "KarriTehas"},  
  {name:  "KebabPizza"},  
  {name:  "Kohtu Kohvik"},  
  {name:  "Kohvik Paul"},  
  {name:  "Kohvik Paviljon"},  
  {name:  "Kohvik Rabarber"},  
  {name:  "Kohvik Spargel"},  
  {name:  "Kotka Kelder"},  
  {name:  "Krempel Kohvik"},  
  {name:  "Lihuniku äri ja restoran"},  
  {name:  "Loorber"},  
  {name:  "MP Bufee"},  
  {name:  "Mandala Restoran"},  
  {name:  "Meat Market"},  
  {name:  "Newton Kohvik"},  
  {name:  "Pahad Poisid"},  
  {name:  "Peipsimaa maitseelamused take away"},  
  {name:  "Pierre"},  
  {name:  "Polpo"},  
  {name:  "Pubi RP9"},  
  {name:  "Püssirohukelder"},  
  {name:  "Rahwa Resto"},  
  {name:  "Rebase Söögituba"},  
  {name:  "Reeda Pagari kohvik"},  
  {name:  "Restoran Tšehhov"},  
  {name:  "Reval Café Tartu"},  
  {name:  "Ristiisa Pubi"},  
  {name:  "SPARK Cafe"},  
  {name:  "Sepa Kohvik"},  
  {name:  "Sheriff Saloon"},  
  {name:  "Suudlevad tudengid"},  
  {name:  "Tartu Kohvik"},  
  {name:  "Tartu Kõrgema Kunstikooli kohvik"},  
  {name:  "Tartu Ränduri pubi"},  
  {name:  "Taverna"},  
  {name:  "Tera Kohvik"},  
  {name:  "Trikster Tihane kohvik-resto"},  
  {name:  "Umb Roht"},  
  {name:  "V café"},  
  {name:  "Vaga Mama"},  
  {name:  "Vapiano"},  
  {name:  "Vene Restoran Vassilissa"},  
  {name:  "Vilde ja Vine"},  
  {name:  "Villa Margaretha"},  
  {name:  "Werner"},  
  {name:  "YliCool"},  
  {name:  "Ülikooli kohvik"}
])
